### ISSUE TITLE
alba output to json format is incorrect when error occurs

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/alba#265]
alba version: 0.9.11

When alba returns an error the output is not in the correct json format
```
root@perf-roub-03:~# alba proxy-statistics -h 178.33.62.163 -p 26204 --to-json
2016-06-28 15:21:28 502464 +0200 - perf-roub-03 - 22476/0 - alba/cli - 0 - warning - (Unix.Unix_error "Connection refused" connect "")
alba: internal error, uncaught exception:
      (Unix.Unix_error "Connection refused" connect "")
      Raised at file "src/core/lwt.ml", line 789, characters 22-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
```

json error:
```
2016-06-28 15:03:56 37300 +0200 - perf-roub-03 - 31923/139765170333504 - extensions/albacli - 2 - ERROR - Error: No JSON object could be decoded
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 68, in run
    output = json.loads(unicode(ex.output, 'latin-1'))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by toolslive** [comment]
The problem occurs when the cli is not able to connect to the respective component (proxy or asd).
A fix is in branch `bug#265`
