### ISSUE TITLE
Proxy hangs on read system call

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba#351]
The proxy was hanging and we investigated:
```
lsof -p 26810
...
alba    26810 root  127u   CHR   10,56      0t0     477 /dev/infiniband/rdma_cm
alba    26810 root  128r  0000    0,11        0    8113 anon_inode
alba    26810 root  129u   CHR   10,56      0t0     477 /dev/infiniband/rdma_cm
alba    26810 root  130u   CHR   10,56      0t0     477 /dev/infiniband/rdma_cm
alba    26810 root  131u  IPv4 3739648      0t0     TCP cmp03:35736->172.19.12.202:8610 (ESTABLISHED)
alba    26810 root  132r  0000    0,11        0    8113 anon_inode
alba    26810 root  133u  IPv4 3747461      0t0     TCP cmp03:35790->172.19.12.203:8636 (ESTABLISHED)
alba    26810 root  134u   CHR   10,56      0t0     477 /dev/infiniband/rdma_cm
alba    26810 root  135r  0000    0,11        0    8113 anon_inode
alba    26810 root  136r  0000    0,11        0    8113 anon_inode
alba    26810 root  137r  0000    0,11        0    8113 anon_inode
alba    26810 root  138r  0000    0,11        0    8113 anon_inode
alba    26810 root  139u   CHR   10,56      0t0     477 /dev/infiniband/rdma_cm
alba    26810 root  140r  0000    0,11        0    8113 anon_inode
```

```
root@cmp03:~# strace -p 26810
Process 26810 attached
read(132, ^CProcess 26810 detached
 <detached ...>
```

```
(gdb) bt
#0  0x00007fd0dcbdb3ad in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fd0d9e5e1f3 in read (__nbytes=8, __buf=0x7ffcc0ccda40, __fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#2  __ibv_get_cq_event (channel=<optimized out>, cq=0x7ffcc0ccda70, cq_context=0x7ffcc0ccda78) at src/verbs.c:484
#3  0x00007fd0db685394 in ?? () from /usr/lib/librdmacm.so.1
#4  0x00007fd0db686ec0 in ?? () from /usr/lib/librdmacm.so.1
#5  0x00007fd0db68a23e in rshutdown () from /usr/lib/librdmacm.so.1
#6  0x00007fd0db68bc1a in rclose () from /usr/lib/librdmacm.so.1
#7  0x0000000000d805b4 in ordma_rclose (fd=<optimized out>) at ordma_close.c:28
#8  0x0000000000cd24df in camlLwt_rsocket__close_1881 () at lwt_rsocket.ml:113
#9  0x00000000007f48a9 in camlLwt_pool2__fun_1507 () at src/tools/lwt_pool2.ml:93
```

**Comment by kinvaris** [comment]
We found this on an environment with mixed transport types. Normal communication goes via TCP. RORA goes via RDMA

**Comment by domsj** [comment]
fwiw the tcp flavour is tcp over rdma, so the rdma stack is still involved

**Comment by domsj** [comment]
@kinvaris have you still seen this issue? I think it will also disappear by following the suggestion in https://github.com/openvstorage/alba/issues/314#issuecomment-246667950 (setting that env var).

**Comment by wimpers** [comment]
@domsj what is the effect of this one? Can we close it down as it hasn't popped up lately right?

**Comment by domsj** [comment]
The effect is a non functioning proxy. Indeed I think we can close this ticket

**Comment by wimpers** [comment]
Closing this issue. Please re-open if it would happen again.
