### ISSUE TITLE
alba proxy dumping core after SEGV

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/alba#508]
```
Dec 15 22:54:21 ftcmp04 systemd[1]: Started Process Core Dump (PID 16656/UID 0).
Dec 15 22:54:21 ftcmp04 systemd[1]: ovs-albaproxy_vp1.service: Main process exited, code=dumped, status=11/SEGV
Dec 15 22:54:21 ftcmp04 systemd[1]: ovs-albaproxy_vp1.service: Unit entered failed state.
Dec 15 22:54:21 ftcmp04 systemd[1]: ovs-albaproxy_vp1.service: Failed with result 'core-dump'.
Dec 15 22:54:26 ftcmp04 systemd[1]: ovs-albaproxy_vp1.service: Service hold-off time over, scheduling restart.
Dec 15 22:54:26 ftcmp04 systemd[1]: Stopping Open vStorage StorageDriver...
Dec 15 22:54:26 ftcmp04 systemd[1]: ovs-volumedriver_vp1.service: Control process exited, code=exited status=1
Dec 15 22:54:53 ftcmp04 systemd[1]: Started Session 159418 of user root.
Dec 15 22:54:57 ftcmp04 systemd[1]: ovs-volumedriver_vp1.service: State 'stop-sigterm' timed out. Killing.
Dec 15 22:54:57 ftcmp04 systemd[1]: ovs-volumedriver_vp1.service: Main process exited, code=killed, status=9/KILL
```

```
root@ftcmp04:/var/log# grep 'Started Process Core Dump' syslog.1
Dec 15 09:11:03 ftcmp04 systemd[1]: Started Process Core Dump (PID 25714/UID 0).
Dec 15 22:54:21 ftcmp04 systemd[1]: Started Process Core Dump (PID 16656/UID 0).
```
 (no dumps on the other nodes)

```
Dec 15 09:11:03 ftcmp04 systemd[1]: ovs-albaproxy_vp1.service: Main process exited, code=dumped, status=11/SEGV
Dec 15 09:11:03 ftcmp04 systemd[1]: ovs-albaproxy_vp1.service: Unit entered failed state.
Dec 15 09:11:03 ftcmp04 systemd[1]: ovs-albaproxy_vp1.service: Failed with result 'core-dump'.
```

**Comment by dejonghb** [comment]
```
root@ftcmp04:~# cat /proc/sys/kernel/core_pattern 
|/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %e
root@ftcmp04:~# coredumpctl list
No coredumps found.
```

**Comment by domsj** [comment]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000e193fc in mark_slice ()
[Current thread is 1 (Thread 0x7fdf2d9d0940 (LWP 16021))]
(gdb) bt
#0  0x0000000000e193fc in mark_slice ()
#1  0x0000000000e1a172 in caml_major_collection_slice ()
#2  0x0000000000e1c231 in caml_alloc_string ()
#3  0x0000000000da3101 in camlBytes__sub_1229 () at bytes.ml:62
#4  0x0000000000d836d3 in camlLwt_log_core__aux_2560 () at string.ml:41
#5  0x0000000000d83761 in camlLwt_log_core__fun_3268 () at src/logger/lwt_log_core.ml:311
#6  0x0000000000d8afba in camlLwt__with_value_28935 () at src/core/lwt.ml:1169
#7  0x0000000000885cba in camlAsd_client__do_request_3886 () at src/asd_client.ml:81
#8  0x0000000000885026 in camlAsd_client__fun_10470 () at src/asd_client.ml:457
#9  0x0000000000d8945c in camlLwt__catch_8694 () at src/core/lwt.ml:686
#10 0x000000000083f4bf in camlAlba_client_upload__fun_13814 () at src/alba_client_upload.ml:642
#11 0x00000000008508af in camlLwt_pool2__fun_1488 () at src/tools/lwt_pool2.ml:73
#12 0x0000000000d8945c in camlLwt__catch_8694 () at src/core/lwt.ml:686
#13 0x0000000000d899d4 in camlLwt__try_bind_13734 () at src/core/lwt.ml:769
#14 0x0000000000d8945c in camlLwt__catch_8694 () at src/core/lwt.ml:686
#15 0x0000000000d8d166 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#16 0x0000000000d8d186 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#17 0x0000000000d8d186 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#18 0x0000000000d8d186 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#19 0x0000000000d8d186 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#20 0x0000000000d8d186 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#21 0x0000000000d8d186 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#22 0x0000000000d8d186 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#23 0x0000000000d8d166 in camlLwt_list__iteri_p_1314 () at src/core/lwt_list.ml:56
#24 0x0000000000d8945c in camlLwt__catch_8694 () at src/core/lwt.ml:686
#25 0x0000000000841891 in camlAlba_client_upload__cleanup_gc_tags_8074 () at src/alba_client_upload.ml:621
#26 0x00000000008418e9 in camlAlba_client_upload__store_manifest_epilogue_8089 () at src/alba_client_upload.ml:663
#27 0x0000000000da19b1 in camlList__iter_1258 () at list.ml:77
#28 0x000000000082771a in camlAlba_client_sequence__fun_8575 () at src/alba_client_sequence.ml:104
#29 0x0000000000d860f6 in camlLwt__fun_32562 () at src/core/lwt.ml:653
#30 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#31 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#32 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#33 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#34 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#35 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#36 0x0000000000d87b99 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:206
#37 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#38 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#39 0x0000000000d87bc7 in camlLwt__run_waiters_rec_1372 () at src/core/lwt.ml:201
#40 0x0000000000d87e3b in camlLwt__leave_wakeup_1425 () at src/core/lwt.ml:289
#41 0x0000000000da74dc in camlArray__iter_1247 () at array.ml:80
#42 0x0000000000e2e37e in caml_start_program ()
#43 0x0000000000e29ff9 in caml_callback ()
#44 0x00007fdf2c378d73 in ev_invoke_pending () from /usr/lib/x86_64-linux-gnu/libev.so.4
#45 0x0000000000e07de4 in lwt_libev_loop (val_loop=<optimized out>, val_block=<optimized out>) at src/unix/lwt_libev_stubs.c:98
#46 0x0000000000d66d59 in camlLwt_engine__fun_2546 () at src/unix/lwt_engine.ml:151
#47 0x0000000000d69118 in camlLwt_main__run_1324 () at src/unix/lwt_main.ml:41
#48 0x00000000009ffbcc in camlCmdliner__eval_term_33714 () at src/cmdliner.ml:1350
#49 0x0000000000a00117 in camlCmdliner__eval_choice_34756 () at src/cmdliner.ml:1390
#50 0x00000000007455fd in camlAlba__entry () at src/alba.ml:913
#51 0x0000000000733839 in caml_program ()
#52 0x0000000000e2e37e in caml_start_program ()
#53 0x0000000000e15e7d in caml_main ()
#54 0x000000000073091c in main ()
```

**Comment by wimpers** [comment]
@domsj what is the probem/use case where this happens? Do we need to fix in RC4?

**Comment by domsj** [comment]
It can happen during normal operation of the proxy. I have no idea what triggers it and/or how to fix it.
The good news is that the proxy will restart and start taking requests again.

**Comment by wimpers** [comment]
Discussed with @saelbrec : can you investigate a bit more as we feel uncomfortable putting things in the field which restarts suddenly.
