### ISSUE TITLE
Rora segfaults when enabled in combination with a global backend

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#560]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7d74a8e36e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
[Current thread is 1 (Thread 0x7f7d14ff9700 (LWP 22306))]
(gdb) bt
#0  0x00007f7d74a8e36e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000bd8529 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__str=..., this=0x7f7d14ff5d30) at /usr/include/c++/5/bits/basic_string.h:1095
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str=..., this=0x7f7d14ff5d30) at /usr/include/c++/5/bits/basic_string.h:551
#3  alba::proxy_client::RoraProxy_client::_process (this=this@entry=0x7f7cb80009c0, object_infos=std::vector of length 1, capacity 1 = {...}, namespace_="937a94dc-87c2-460c-b826-77db6ffb6e2e")
    at ../src/lib/rora_proxy_client.cc:339
#4  0x0000000000bd88c2 in alba::proxy_client::RoraProxy_client::apply_sequence (this=0x7f7cb80009c0, namespace_="937a94dc-87c2-460c-b826-77db6ffb6e2e", write_barrier=<optimized out>, asserts=..., updates=...)
    at ../src/lib/rora_proxy_client.cc:413
#5  0x0000000000b01c54 in backend::albaconn::Connection::<lambda()>::operator() (__closure=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/backend/Alba_Connection.cpp:696
#6  backend::albaconn::Connection::convert_exceptions_<void, backend::albaconn::Connection::write_tag_(const backend::Namespace&, const boost::filesystem::path&, const string&, const youtils::UniqueObjectTag*, OverwriteObject)::<lambda()> > (desc=0xe1f6f2 "write tag", this=0x7f7cb80026e0, fun=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/backend/Alba_Connection.cpp:185
#7  backend::albaconn::Connection::write_tag_ (this=0x7f7cb80026e0, nspace=..., src=..., name="owner_tag", prev_tag=<optimized out>, overwrite=OverwriteObject::T)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/backend/Alba_Connection.cpp:697
#8  0x0000000000aac5a5 in backend::BackendConnectionInterface::write_tag (this=0x7f7cb80026e0, nspace=..., src=..., name="owner_tag", prev_tag=prev_tag@entry=0x0, overwrite=OverwriteObject::T)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/backend/BackendConnectionInterface.cpp:283
#9  0x0000000000ab0425 in backend::BackendInterface::do_wrap_<backend::(anonymous namespace)::NamespaceConnFetcher, std::unique_ptr<youtils::UniqueObjectTag>, backend::Namespace const&, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, youtils::UniqueObjectTag const*, OverwriteObject> (get_conn=<synthetic pointer>, mem_fun=<optimized out>, params=..., this=0x7f7cb8002a80)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:81
#10 backend::BackendInterface::wrap_<std::unique_ptr<youtils::UniqueObjectTag, std::default_delete<youtils::UniqueObjectTag> >, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, youtils::UniqueObjectTag const*, OverwriteObject> (mem_fun=<optimized out>, params=..., this=0x7f7cb8002a80)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:174
#11 backend::BackendInterface::write_tag (this=0x7f7cb8002a80, src=..., name="owner_tag", prev_tag=prev_tag@entry=0x0, overwrite=overwrite@entry=OverwriteObject::T, params=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/backend/BackendInterface.cpp:504
#12 0x00000000008989e0 in volumedriver::VolumeFactory::claim_namespace (nspace=..., owner_tag=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/volumedriver/VolumeFactory.cpp:319
#13 0x00000000008a450b in volumedriver::VolumeFactory::createNewVolume (config=...)
```

```
Jan 10 11:02:28 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:02:28 003801 +0100 - ovs-node01-1604 - 9638/0x00007fd699ffb700 - volumedriverfs/LockedArakoon - 000000000000011b - info - run_sequence: collect garbage succeeded after 1 attempt(s)
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 041139 +0100 - ovs-node01-1604 - 9638/0x00007fd67bfff700 - volumedriverfs/MTServer - 000000000000011c - info - work: You have 1 connections running
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 041199 +0100 - ovs-node01-1604 - 9638/0x00007fd67bfff700 - volumedriverfs/MTServer - 000000000000011d - info - cleanup_threads_locked: Trying to join 1 threads
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 041451 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/XMLRPCTimingWrapper - 000000000000011e - info - execute: Arguments for volumeCreate are {[metadata_backend_config:FgAAAAAAAABzZXJpYWxpemF0aW9uOjphcmNoaXZlDAAECAQIAQAAAAAAAAAAAQAmAAAAAAAA
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: AHZvbHVtZWRyaXZlcjo6TURTTWV0YURhdGFCYWNrZW5kQ29uZmlnAQMAAAAAAAAAAAAAAAAB
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: AAAAAAAAAAEAAAAAAQAAAA4AAAAAAAAAMTAuMTAwLjE5OS4xNzG8ZgEAAAAUAAAAAAAAAA==,target_path:/testing.raw,volume_size:1073741824B,vrouter_cluster_id:b7d9ef27-e7fa-44b2-ac93-28bbecb3c9e7,vrouter_id:myvpool016buFv81Lo91PenHB]}
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 041541 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/XMLRPCRedirectWrapper - 000000000000011f - info - execute: Execution on myvpool016buFv81Lo91PenHB requested
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 041581 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/XMLRPCRedirectWrapper - 0000000000000120 - info - execute: Node ID myvpool016buFv81Lo91PenHB is ours - good
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 041686 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/FileSystem - 0000000000000121 - info - create_volume: Trying to create volume of size 1073741824 @ "/testing.raw"
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 045031 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/LockedArakoon - 0000000000000122 - info - run_sequence: updating counter succeeded after 1 attempt(s)
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 045096 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/FileSystem - 0000000000000123 - info - create_volume_or_clone_: Trying to create volume or clone a03cbc69-9125-481e-b7e9-b759ca340c0c @ "/testing.raw"
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 045879 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/VFSObjectRouter - 0000000000000124 - info - create: Creating Volume-a03cbc69-9125-481e-b7e9-b759ca340c0c
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 045936 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/ObjectRegistry - 0000000000000125 - info - register_base_volume: b7d9ef27-e7fa-44b2-ac93-28bbecb3c9e7/myvpool016buFv81Lo91PenHB: registering a03cbc69-9125-481e-b7e9-b759ca340c0c, namespace a03cbc69-9125-481e-b7e9-b759ca340c0c, foc config mode Automatic
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 047939 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/LockedArakoon - 0000000000000126 - info - run_sequence: updating counter succeeded after 1 attempt(s)
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 049847 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/LockedArakoon - 0000000000000127 - info - run_sequence: register basic volume succeeded after 1 attempt(s)
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 049934 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/VolManager - 0000000000000128 - notice - New Volume, VolumeId: a03cbc69-9125-481e-b7e9-b759ca340c0c, Namespace: a03cbc69-9125-481e-b7e9-b759ca340c0c, Size: 0, CreateNamespace: CreateNamespace::T, START
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 050060 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/AlbaProxyClient - 0000000000000129 - info - logMessage: TCPProxy_client(10.100.199.171, 26205)
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 050314 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/AlbaProxyClient - 000000000000012a - info - logMessage: RoraProxy_client(...)
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 050356 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/BackendConnectionInterfaceLogger - 000000000000012b - info - Logger: Entering namespaceExists a03cbc69-9125-481e-b7e9-b759ca340c0c
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 054767 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/BackendConnectionInterfaceLogger - 000000000000012c - info - ~Logger: Exiting namespaceExists for a03cbc69-9125-481e-b7e9-b759ca340c0c
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 054899 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/BackendConnectionInterfaceLogger - 000000000000012d - info - Logger: Entering createNamespace a03cbc69-9125-481e-b7e9-b759ca340c0c
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 125036 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/BackendConnectionInterfaceLogger - 000000000000012e - info - ~Logger: Exiting createNamespace for a03cbc69-9125-481e-b7e9-b759ca340c0c
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 125107 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/VolManager - 000000000000012f - info - getMaxFileDescriptors_: Maximum number of open file descriptors: 65536, could be raised to 65536
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 125142 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/VolManager - 0000000000000130 - info - volumePotentialSCOCache: We have enough room for an additional 13 volumes with cluster size 4096, SCO multiplier 1024 (= SCO size 4194304), TLog multiplier 16
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 125368 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/BackendConnectionInterfaceLogger - 0000000000000131 - info - Logger: Entering write_tag a03cbc69-9125-481e-b7e9-b759ca340c0c owner_tag
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 135575 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/AlbaProxyClient - 0000000000000132 - info - logMessage: OsdAccess::update:: filling up
Jan 10 11:04:45 ovs-node01-1604 volumedriver_fs.sh[9638]: 2017-01-10 11:04:45 135754 +0100 - ovs-node01-1604 - 9638/0x00007fd65d7fa700 - volumedriverfs/AlbaProxyClient - 0000000000000133 - info - logMessage: OSDAccess::update: exception while filling up: unexpected kind while deserializing OsdInfo
Jan 10 11:04:45 ovs-node01-1604 systemd[1]: ovs-volumedriver_myvpool01.service: Main process exited, code=killed, status=11/SEGV
Jan 10 11:04:45 ovs-node01-1604 bash[10550]: b7d9ef27-e7fa-44b2-ac93-28bbecb3c9e7 on /mnt/myvpool01 type fuse.b7d9ef27-e7fa-44b2-ac93-28bbecb3c9e7 (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
Jan 10 11:04:45 ovs-node01-1604 systemd[1]: ovs-volumedriver_myvpool01.service: Unit entered failed state.
Jan 10 11:04:45 ovs-node01-1604 systemd[1]: ovs-volumedriver_myvpool01.service: Failed with result 'signal'.

ii  libovsvolumedriver                   6.7.1-0                             amd64        VolumeDriver client library
ii  volumedriver-no-dedup-base           6.7.1-0                             amd64        VolumeDriver common infrastructure
ii  volumedriver-no-dedup-server         6.7.1-0                             amd64        VolumeDriver daemon and helpers

version: 6.7.1
version revision: 61badf6887992a645a2e449f57e71711a0969800
branch: master
md5 support: no
revision: f6d0e7ba31ae3d17c93659abee636081394d625a
build time: Tue Jan  3 19:27:09 UTC 2017
```

**Comment by domsj** [comment]
fixed by #561
